"""Public-SI capture route diagrams and a conserved, origin-specific carbon ledger."""

import json
from pathlib import Path
from urllib.parse import quote

from dash import html

from .bau import DETAIL as FUEL, _box, _utility_icon
from .diagrams import COLORS, _arrow, _svg, _text, _icon as _process_icon
from .overview import ORIGINS, _icon

DETAIL = json.loads(
    (
        Path(__file__).resolve().parents[1] / "data/public/capture_details_2025.json"
    ).read_text()
)


def _process(x, y, w, kind, title, note, tone="carbon", compact=False):
    h = 70 if compact else 110
    b = _box(x, y, w, h)
    if compact:
        b += _icon(kind, x + 8, y + 8, 45, tone)
        b += _text(x + 62, y + 28, title, "label") + _text(x + 62, y + 49, note, "note")
    else:
        b += _icon(kind, x + w / 2 - 28, y + 6, 56, tone)
        b += _text(x + w / 2, y + 81, title, "node-title", "middle")
        b += _text(x + w / 2, y + 101, note, "note", "middle")
    return b


def _origin_arrow(path, index):
    key, color, _ = ORIGINS[index]
    return f'<path data-origin="{key}" d="{path}" fill="none" stroke="{color}" stroke-width="2.8" stroke-linejoin="round" marker-end="url(#origin-{key})"/>'


def capture_svg(system):
    if system not in DETAIL["systems"]:
        raise ValueError(system)
    ccus = system == "CCUS"
    b = (
        "<defs>"
        + "".join(
            f'<marker id="origin-{key}" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto" markerUnits="userSpaceOnUse"><path d="M0 0 7 3.5 0 7Z" fill="{color}"/></marker>'
            for key, color, _ in ORIGINS
        )
        + "</defs>"
    )
    b += '<rect x="8" y="8" width="1384" height="366" rx="15" fill="white" stroke="#aebfc7" stroke-dasharray="7 5"/>'
    b += _text(25, 28, "COMPLETE PRODUCT SYSTEM", "boundary")
    b += _text(
        1370, 28, "2025 illustration · same kiln and fuel mix as BAU", "boundary", "end"
    )
    b += '<rect x="24" y="42" width="270" height="316" rx="12" fill="#faf5eb"/>'
    b += _text(40, 62, "BACKGROUND · INPUT SUPPLY", "boundary")
    b += _icon("quarry", 42, 77, 46) + _text(101, 96, "Limestone (chalk)", "node-title")
    b += _text(101, 119, "≈ 1,300 kg slurry (rounded)", "note")
    b += _icon("fuel", 42, 139, 43) + _text(
        100, 157, "Same kiln fuel mix", "node-title"
    )
    b += _text(100, 179, f'{FUEL["kiln_energy"]["value"]:.2f} GJ per tonne clinker', "note")
    b += _text(42, 207, "CO₂ generated by kiln fuels", "label")
    for y, key, label, tone in (
        (231, "fuel_fossil", "Fossil fuel", "fossil"),
        (254, "fuel_non_fossil", "Non-fossil fuel", "bio"),
    ):
        b += f'<circle cx="47" cy="{y-5}" r="4" fill="{COLORS[tone]}"/>'
        b += _text(59, y, label, "note")
        b += _text(277, y, f'{FUEL["emissions"][key]["value"]:.0f} kg', "label", "end")
    b += _utility_icon("boiler", 38, 283, 48)
    b += _text(98, 300, "Extra capture heat", "label")
    b += _text(98, 320, "Gas boiler + fossil CO₂", "note")
    b += _text(42, 346, "Calcination / boiler CO₂ unquantified", "note")

    # A connected supply bus, with branches ending on the process boxes.
    b += _box(319, 42, 1055, 47, background=True)
    b += _utility_icon("electricity", 331, 49, 33)
    b += _utility_icon("equipment", 370, 49, 33)
    b += _text(
        414, 70, "Operating electricity, water, materials and equipment", "node-title"
    )
    b += '<rect x="314" y="103" width="1060" height="254" rx="12" fill="#f3f8fa" stroke="#afc7d0" stroke-dasharray="7 5"/>'
    b += _text(328, 123, "FOREGROUND", "boundary")
    b += _box(335, 137, 140, 114)
    b += _icon("kiln", 342, 147, 63)
    b += _text(405, 234, "Rotary kiln", "label", "middle")
    b += _text(405, 269, "1 tonne clinker", "note", "middle")
    b += _arrow("M294 107H305V175H335", "material")
    b += _arrow("M294 166H311V219H335", "energy")
    b += _arrow("M406 89V137", "energy")

    # Preserve all three origins, without importing an undisclosed calcination value.
    b += _text(558, 125, "Flue gas → capture", "note", "middle")
    for i, (y, label) in enumerate(
        (
            (151, "Calcination CO₂"),
            (183, "Fossil fuel CO₂"),
            (215, "Non-fossil fuel CO₂"),
        )
    ):
        b += _origin_arrow(f"M475 {y}H644", i)
        b += _text(487, y - 8, label, "note")
    b += _process(644, 136, 166, "capture", "CO₂ capture", "90% of inlet CO₂")
    b += _arrow("M726 89V136", "energy")
    # Additional steam-source carbon is acknowledged, not hidden in the fuel ledger.
    b += _arrow("M294 308H615V235H644", "fossil")
    b += _arrow("M294 324H629V243H644", "energy")

    if not ccus:
        b += _process(
            922, 136, 191, "ship", "Liquefy & transport", "5%, then 1.44% loss", "storage"
        )
        b += _process(
            1172,
            136,
            190,
            "storage",
            "North Sea storage",
            "No later leakage",
            "storage",
        )
        for index, y in enumerate((174, 183, 192)):
            b += _origin_arrow(f"M810 {y}H922", index)
            b += _origin_arrow(f"M1113 {y}H1172", index)
        b += _arrow("M1018 89V136", "energy") + _arrow("M1267 89V136", "energy")
        b += _icon("atmosphere", 650, 258, 35, "fossil")
        b += _text(
            698,
            278,
            "Uncaptured + conditioning / transport losses → atmosphere",
            "note",
        )
        b += _arrow("M744 246V260", "fossil")
        b += _arrow("M1018 246V260", "fossil")
        b += _text(821, 220, "Captured CO₂", "note")
    else:
        non = DETAIL["systems"][system]["non_fossil_fuel"]
        b += _process(
            922,
            114,
            207,
            "ship",
            "Liquefy & ship",
            "5%, then 1.44% loss",
            "storage",
            compact=True,
        )
        b += _process(
            1180,
            114,
            182,
            "storage",
            "North Sea",
            "Permanent storage",
            "storage",
            compact=True,
        )
        for index, y in enumerate((155, 165)):
            b += _origin_arrow(f"M810 {y}H858V{139+index*9}H922", index)
            b += _origin_arrow(f"M1129 {139+index*9}H1180", index)
        b += _arrow("M1030 89V114", "energy") + _arrow("M1271 89V114", "energy")
        b += _origin_arrow("M810 215H851V204H1051V232", 2)
        b += _text(
            1099,
            202,
            f'{non["captured_c"]*44.009/12.011:.0f} kg non-fossil CO₂ feed',
            "note",
            "end",
        )
        # Electrolysis and methanol are explicit processes, not an invisible utility.
        b += _box(851, 232, 111, 71)
        b += _process_icon("hydrogen", 856, 240, 35, "energy")
        b += _text(920, 260, "H₂", "node-title", "middle")
        b += _text(906, 288, "Electrolysis", "note", "middle")
        b += _box(986, 232, 147, 71)
        b += _process_icon("methanol", 993, 238, 35, "bio")
        b += _text(1080, 257, "Methanol", "label", "middle")
        b += _text(1060, 286, f'{non["methanol_kg"]:.1f} kg methanol', "note", "middle")
        b += _arrow("M962 265H986", "energy")
        b += _process(
            1170,
            232,
            192,
            "jet",
            "Methanol-to-X",
            "Jet + co-products",
            "bio",
            compact=True,
        )
        b += _arrow("M1133 265H1170", "bio")
        b += _text(1248, 225, "85% of methanol carbon → jet", "note", "middle")
        # A white underlay distinguishes the utility crossing from a carbon junction.
        b += '<path d="M891 89V223H906V232" fill="none" stroke="#f3f8fa" stroke-width="7"/>'
        b += _arrow("M891 89V223H906V232", "energy")
        b += _arrow("M1121 184V211", "fossil")
        b += _text(1132, 205, "Losses to air", "note")
        b += _icon("atmosphere", 652, 257, 32, "fossil")
        b += _text(694, 272, "Uncaptured CO₂ → air", "note")
        b += _arrow("M735 246V257", "fossil")
        b += '<path d="M1266 302V309H1030M1266 309H1305" fill="none" stroke="#3e7654" stroke-width="2"/>'
        for x, label in (
            (1030, f'Jet {non["jet_kg"]:.1f} kg'),
            (1164, f'Diesel {non["diesel_kg"]:.2f} kg'),
            (1305, f'Naphtha {non["naphtha_kg"]:.2f} kg'),
        ):
            b += _arrow(f"M{x} 309V316", "bio")
            b += _text(x, 331, label, "note", "middle")

    # Heat serves capture before any surplus is substituted. No private heat value.
    b += (
        '<path d="M356 251V339H663V246" fill="none" stroke="#f3f8fa" stroke-width="7"/>'
    )
    b += _arrow("M356 251V339H663V246", "energy")
    b += _text(527, 353, "Recovered heat first", "note", "middle")
    b += _arrow("M683 246V350H865", "energy")
    b += _icon("heat", 870, 334, 28, "energy")
    b += _text(905, 353, "Surplus heat", "note")
    b += _arrow("M992 348H1048", "energy", dashed=True)
    b += _text(1060, 353, "Displaces gas-boiler heat", "note")
    return _svg(
        b,
        1400,
        382,
        f"{system}: public-SI capture route, all three carbon origins, losses, heat recovery and carbon destinations",
    )


def carbon_ledger(system):
    columns = (
        ("known_air_c", "Air now*" if system == "CCUS" else "Air now"),
        ("stored_c", "Stored"),
        ("jet_c", "In jet fuel"),
        ("diesel_c", "In diesel"),
        ("naphtha_c", "In naphtha"),
    )
    if system == "CCS":
        columns = columns[:2]
    rows = []
    for origin, label in (
        ("fossil_fuel", "Fossil fuel carbon"),
        ("non_fossil_fuel", "Non-fossil fuel carbon"),
    ):
        values = DETAIL["systems"][system][origin]
        rows.append(
            html.Tr(
                [
                    html.Th(label, scope="row"),
                    html.Td(f'{values["inlet_c"]:.1f}', className="carbon-inlet"),
                    *[
                        html.Td(f"{values[key]:.1f}", className="carbon-" + key)
                        for key, _ in columns
                    ],
                ]
            )
        )
    return html.Div(
        [
            html.Div(
                [
                    html.Strong("Fuel-carbon balance only"),
                    html.Span("kg C per tonne clinker · carbon mass, not a GWP score"),
                ],
                className="carbon-ledger-heading",
            ),
            html.Table(
                [
                    html.Thead(
                        html.Tr(
                            [
                                html.Th("Origin"),
                                html.Th("Input ="),
                                *[html.Th(label) for _, label in columns],
                            ]
                        )
                    ),
                    html.Tbody(rows),
                ]
            ),
        ],
        className="carbon-ledger",
    )


def capture_detail(system):
    if system == "CCUS":
        non = DETAIL["systems"][system]["non_fossil_fuel"]
        note = html.Div(
            [
                html.Strong(f'{non["jet_kg"]:.1f} kg jet fuel'),
                html.Span("→ used one year later →"),
                html.Strong(f'{non["jet_combustion_co2_kg"]:.0f} kg non-fossil CO₂'),
                html.Span(
                    f'*Includes {non["assumed_residual_co2_kg"]:.0f} kg CO₂ from burning the remaining carbon this year, as assumed here. No heat credit.'
                ),
            ],
            className="capture-fuel-use",
        )
    else:
        note = html.P(
            "90% capture → 5% liquefaction loss → 1.44% loss of loaded CO₂ in transport. Rates follow the published SI.2 inventory.",
            className="capture-balance-note",
        )
    return html.Div(
        [
            html.Figure(
                html.Img(
                    src="data:image/svg+xml;charset=utf-8,"
                    + quote(capture_svg(system)),
                    alt=f"{system} carbon routing with a fuel-carbon ledger. Calcination and steam-supply carbon are not quantified.",
                    className="system-svg",
                ),
                className="capture-detail-figure",
            ),
            carbon_ledger(system),
            *([uop_route()] if system == "CCUS" else []),
            note,
            html.P(
                "Calcination and capture-boiler carbon are not quantified here."
                + (
                    " All three fuels burn one year later."
                    if system == "CCUS"
                    else ""
                ),
                className="capture-basis-note",
            ),
        ],
        className="capture-detail-layout" + (" capture-detail-uop" if system == "CCUS" else ""),
    )


def uop_route():
    """Patent-supported topology, without inventing a quantified gas split."""
    return html.Div(
        [
            html.A("UOP · olefin recycle ↗", href="https://patents.justia.com/patent/20260098223", target="_blank", rel="noopener noreferrer", title="UOP patent: unconverted light olefins return to the process"),
            html.Div([
                html.Span("Methanol → olefins"), html.Span("→", className="uop-arrow"),
                html.Span("Separate"), html.Span("→", className="uop-arrow"),
                html.Span("Join carbon chains"), html.Span("→", className="uop-arrow"),
                html.Span("Add H₂ and separate fuels"),
            ], className="uop-steps"),
            html.Div([
                html.Span("↶ Unconverted light olefins return to the process"),
                html.Span("↘ Remaining carbon → CO₂ when fuel is produced*"),
            ], className="uop-branches"),
            html.Div([
                html.Img(src="data:image/svg+xml;charset=utf-8," + quote(_svg(_utility_icon("boiler", 0, 0, 36), 40, 40, "Natural gas boiler")),
                         style={"width": "28px", "height": "28px"}),
                html.Strong("Gas boiler → fuel-conversion heat"),
                html.Span("0.97 MJ/kg methanol · uncaptured boiler CO₂ · no recovery credit"),
                html.A("Methanol: JRC99380 ↗", href="https://publications.jrc.ec.europa.eu/repository/bitstream/JRC99380/ld1a27629enn.pdf", target="_blank"),
            ], className="uop-heat-service"),
        ], className="uop-route",
    )
